name: Up
on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+.*"

jobs:
  build_binary:
    runs-on: macOS-latest
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly-2020-03-19
    - run: echo "HELLO WORLD"
